// Demo data — usato quando NEXT_PUBLIC_DEMO_MODE=true o env Supabase mancanti/fake
import type { Cliente, Contenuto, Prodotto, Setting, LogPubblicazione, BlogArticolo, SeoAudit } from './types'
import { isDemo } from './demo'

export const isDemoMode = isDemo

export const demoContenuti: Contenuto[] = [
  {
    id: '1', cliente_id: 'demo-silkincom', id_contenuto: 'C001',
    data_pubblicazione: '2026-05-24', ora_pubblicazione: '12:30',
    canale: 'instagram', formato: 'post', obiettivo: 'ispirazione',
    product_id: 'P001', nome_prodotto: 'Blazer in lino', tema: 'Outfit elegante da giorno',
    hook: 'Il capo che rende elegante anche il look più semplice',
    caption: 'Un blazer leggero, una base pulita e il look è fatto. Un must per chi cerca versatilità senza rinunciare allo stile.\n\nScoprilo ora sul sito.',
    hashtag: '#outfit #moda #fashion #blazer #stileitaliano #ootd #minimalstyle #womensfashion',
    cta: 'Scoprilo ora sul sito',
    link_media_1: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400',
    link_media_2: null, link_media_3: null, link_media_4: null, link_media_5: null, link_media_6: null, link_media_7: null, link_media_8: null, link_media_9: null, link_media_10: null,
    link_prodotto: 'https://example.com/p/blazer-lino', link_prodotto_finale: null,
    status: 'DA_APPROVARE',
    approvato_da: null, data_approvazione: null, blotato_post_id: null,
    errore: null, note: null, platform_account_id: null, publish_lock_id: null,
    media_type: 'image', media_validato: 'SI',
    retry_count: 0, last_retry_at: null, errore_tecnico: null,
    checked_copy: null, checked_media: null, checked_link: null, checked_price: null,
    checked_by: null, checked_at: null,
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null,
    promo_id: null, promo_codice: null, promo_validata: null,
    fonte_media: 'foto_prodotto_propria', consenso_utilizzo: 'SI',
    scenes_json: null, slides_json: null, overlay_text: null, alt_text: null, tags: null, thumbnail_url: null,
    idea_visual: null, voiceover_script: null, music_mood: null,
    checked_alt_text: null, checked_aspect_ratio: null, checked_media_valid: null,
    blotato_scheduled_at: null,
    blotato_status: null, blotato_post_url: null, blotato_sync_at: null,
    created_at: '2026-05-23T08:00:00Z', updated_at: '2026-05-23T08:00:00Z',
  },
  {
    id: '2', cliente_id: 'demo-silkincom', id_contenuto: 'C002',
    data_pubblicazione: '2026-05-24', ora_pubblicazione: '18:00',
    canale: 'instagram', formato: 'carousel', obiettivo: 'awareness',
    product_id: 'P002', nome_prodotto: 'Jeans dritti vita alta', tema: 'Denim essenziale',
    hook: '5 modi di portare il jeans dritto vita alta',
    caption: 'Il capo passe-partout del guardaroba. Casual, elegante o sporty — funziona sempre.\n\nSwipe per scoprire gli abbinamenti.',
    hashtag: '#jeans #denim #outfit #fashion #styletips #ootd',
    cta: 'Salva il post per ispirarti',
    link_media_1: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
    link_media_2: 'https://images.unsplash.com/photo-1582418702059-97ebafb35d09?w=400',
    link_media_3: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400',
    link_media_4: null, link_media_5: null, link_media_6: null, link_media_7: null, link_media_8: null, link_media_9: null, link_media_10: null,
    link_prodotto: 'https://example.com/p/jeans-dritti', link_prodotto_finale: null,
    status: 'DA_APPROVARE',
    approvato_da: null, data_approvazione: null, blotato_post_id: null,
    errore: null, note: null, platform_account_id: null, publish_lock_id: null,
    media_type: 'image', media_validato: 'SI',
    retry_count: 0, last_retry_at: null, errore_tecnico: null,
    checked_copy: null, checked_media: null, checked_link: null, checked_price: null,
    checked_by: null, checked_at: null,
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null,
    promo_id: null, promo_codice: null, promo_validata: null,
    fonte_media: 'foto_prodotto_propria', consenso_utilizzo: 'SI',
    scenes_json: null, slides_json: null, overlay_text: null, alt_text: null, tags: null, thumbnail_url: null,
    idea_visual: null, voiceover_script: null, music_mood: null,
    checked_alt_text: null, checked_aspect_ratio: null, checked_media_valid: null,
    blotato_scheduled_at: null,
    blotato_status: null, blotato_post_url: null, blotato_sync_at: null,
    created_at: '2026-05-23T08:00:00Z', updated_at: '2026-05-23T08:00:00Z',
  },
  {
    id: '3', cliente_id: 'demo-silkincom', id_contenuto: 'C003',
    data_pubblicazione: '2026-05-23', ora_pubblicazione: '10:00',
    canale: 'tiktok', formato: 'reel', obiettivo: 'engagement',
    product_id: 'P003', nome_prodotto: 'T-shirt cotone bio', tema: 'Mini haul',
    hook: 'POV: hai trovato la t-shirt perfetta',
    caption: 'Una sola t-shirt. Tre look diversi. Cotone bio certificato.',
    hashtag: '#tshirt #cotonebio #sustainable #ootd #pov',
    cta: 'Scoprila in bio',
    link_media_1: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400',
    link_media_2: null, link_media_3: null, link_media_4: null, link_media_5: null, link_media_6: null, link_media_7: null, link_media_8: null, link_media_9: null, link_media_10: null,
    link_prodotto: 'https://example.com/p/tshirt', link_prodotto_finale: 'https://example.com/p/tshirt?utm_source=tiktok&utm_medium=social',
    status: 'PUBBLICATO',
    approvato_da: 'admin', data_approvazione: '2026-05-22T15:00:00Z',
    blotato_post_id: 'blt_xyz_123',
    errore: null, note: null, platform_account_id: 'TT_REAL_ID', publish_lock_id: null,
    media_type: 'video', media_validato: 'SI',
    retry_count: 0, last_retry_at: null, errore_tecnico: null,
    checked_copy: 'SI', checked_media: 'SI', checked_link: 'SI', checked_price: 'SI',
    checked_by: 'admin', checked_at: '2026-05-22T15:00:00Z',
    utm_source: 'tiktok', utm_medium: 'social', utm_campaign: 'social_default', utm_content: 'C003',
    promo_id: null, promo_codice: null, promo_validata: null,
    fonte_media: 'foto_prodotto_propria', consenso_utilizzo: 'SI',
    scenes_json: null, slides_json: null, overlay_text: null, alt_text: null, tags: null, thumbnail_url: null,
    idea_visual: null, voiceover_script: null, music_mood: null,
    checked_alt_text: null, checked_aspect_ratio: null, checked_media_valid: null,
    blotato_scheduled_at: null,
    blotato_status: 'published', blotato_post_url: 'https://instagram.com/p/xyz123', blotato_sync_at: '2026-05-23T10:00:00Z',
    created_at: '2026-05-22T08:00:00Z', updated_at: '2026-05-23T10:00:00Z',
  },
  {
    id: '4', cliente_id: 'demo-silkincom', id_contenuto: 'C004',
    data_pubblicazione: '2026-05-23', ora_pubblicazione: '14:00',
    canale: 'facebook', formato: 'post', obiettivo: 'vendita',
    product_id: 'P001', nome_prodotto: 'Blazer in lino', tema: 'Saldi',
    hook: '20% di sconto sul blazer in lino',
    caption: 'Solo per questo weekend. Il blazer che hai sempre desiderato.',
    hashtag: '#sale #blazer #fashion #saldi',
    cta: 'Approfitta dello sconto',
    link_media_1: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400',
    link_media_2: null, link_media_3: null, link_media_4: null, link_media_5: null, link_media_6: null, link_media_7: null, link_media_8: null, link_media_9: null, link_media_10: null,
    link_prodotto: 'https://example.com/p/blazer-lino', link_prodotto_finale: null,
    status: 'ERRORE',
    approvato_da: 'admin', data_approvazione: '2026-05-23T08:00:00Z', blotato_post_id: null,
    errore: null, note: null, platform_account_id: 'FB_REAL_ID', publish_lock_id: null,
    media_type: 'image', media_validato: 'NO',
    retry_count: 1, last_retry_at: '2026-05-23T14:15:00Z',
    errore_tecnico: 'media KO code=404 — link_media_1 non raggiungibile',
    checked_copy: 'SI', checked_media: 'NO', checked_link: 'SI', checked_price: 'SI',
    checked_by: 'admin', checked_at: '2026-05-23T08:00:00Z',
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null,
    promo_id: null, promo_codice: null, promo_validata: null,
    fonte_media: 'foto_prodotto_propria', consenso_utilizzo: 'SI',
    scenes_json: null, slides_json: null, overlay_text: null, alt_text: null, tags: null, thumbnail_url: null,
    idea_visual: null, voiceover_script: null, music_mood: null,
    checked_alt_text: null, checked_aspect_ratio: null, checked_media_valid: null,
    blotato_scheduled_at: null,
    blotato_status: null, blotato_post_url: null, blotato_sync_at: null,
    created_at: '2026-05-22T08:00:00Z', updated_at: '2026-05-23T14:15:00Z',
  },
  {
    id: '5', cliente_id: 'demo-silkincom', id_contenuto: 'C005',
    data_pubblicazione: '2026-05-25', ora_pubblicazione: '09:00',
    canale: 'pinterest', formato: 'pin', obiettivo: 'traffic',
    product_id: 'P002', nome_prodotto: 'Jeans dritti vita alta', tema: 'Style inspiration',
    hook: 'Il jeans che valorizza ogni silhouette',
    caption: 'Vita alta, taglio dritto, denim premium.',
    hashtag: '#denim #jeansoutfit #fashioninspo',
    cta: 'Shop now',
    link_media_1: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400',
    link_media_2: null, link_media_3: null, link_media_4: null, link_media_5: null, link_media_6: null, link_media_7: null, link_media_8: null, link_media_9: null, link_media_10: null,
    link_prodotto: 'https://example.com/p/jeans-dritti', link_prodotto_finale: null,
    status: 'APPROVATO',
    approvato_da: 'admin', data_approvazione: '2026-05-23T11:00:00Z',
    blotato_post_id: null,
    errore: null, note: null, platform_account_id: null, publish_lock_id: null,
    media_type: 'pin', media_validato: 'SI',
    retry_count: 0, last_retry_at: null, errore_tecnico: null,
    checked_copy: 'SI', checked_media: 'SI', checked_link: 'SI', checked_price: 'SI',
    checked_by: 'admin', checked_at: '2026-05-23T11:00:00Z',
    utm_source: null, utm_medium: null, utm_campaign: null, utm_content: null,
    promo_id: null, promo_codice: null, promo_validata: null,
    fonte_media: 'foto_prodotto_propria', consenso_utilizzo: 'SI',
    scenes_json: null, slides_json: null, overlay_text: null, alt_text: null, tags: null, thumbnail_url: null,
    idea_visual: null, voiceover_script: null, music_mood: null,
    checked_alt_text: null, checked_aspect_ratio: null, checked_media_valid: null,
    blotato_scheduled_at: null,
    blotato_status: 'scheduled', blotato_post_url: null, blotato_sync_at: '2026-05-23T11:00:00Z',
    created_at: '2026-05-22T08:00:00Z', updated_at: '2026-05-23T11:00:00Z',
  },
]

export const demoProdotti: Prodotto[] = [
  {
    id: 'p1', cliente_id: 'demo-silkincom', product_id: 'P001', nome_prodotto: 'Blazer in lino',
    categoria: 'giacche', collezione: 'primavera-estate',
    prezzo: 129, prezzo_promo: null,
    link_prodotto: 'https://example.com/p/blazer-lino',
    link_img_1: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=300',
    link_img_2: null, link_img_3: null,
    colori: 'beige/nero', taglie: 'XS-XL',
    mood: 'elegante', target: 'donna 30+',
    priorita: 'alta', prodotto_attivo: 'SI',
    stock_status: 'disponibile', stock_quantity: 50,
    data_ultimo_controllo_stock: '2026-05-22', note: null,
    created_at: '2026-05-01T00:00:00Z', updated_at: '2026-05-22T00:00:00Z',
  },
  {
    id: 'p2', cliente_id: 'demo-silkincom', product_id: 'P002', nome_prodotto: 'Jeans dritti vita alta',
    categoria: 'jeans', collezione: 'permanente',
    prezzo: 89, prezzo_promo: null,
    link_prodotto: 'https://example.com/p/jeans-dritti',
    link_img_1: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=300',
    link_img_2: null, link_img_3: null,
    colori: 'denim chiaro', taglie: '24-32',
    mood: 'casual', target: 'unisex',
    priorita: 'alta', prodotto_attivo: 'SI',
    stock_status: 'disponibile', stock_quantity: 120,
    data_ultimo_controllo_stock: '2026-05-22', note: null,
    created_at: '2026-05-01T00:00:00Z', updated_at: '2026-05-22T00:00:00Z',
  },
  {
    id: 'p3', cliente_id: 'demo-silkincom', product_id: 'P003', nome_prodotto: 'T-shirt cotone bio',
    categoria: 't-shirt', collezione: 'sostenibile',
    prezzo: 39, prezzo_promo: 29,
    link_prodotto: 'https://example.com/p/tshirt',
    link_img_1: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=300',
    link_img_2: null, link_img_3: null,
    colori: 'bianco/nero/oliva', taglie: 'XS-XXL',
    mood: 'casual', target: 'unisex',
    priorita: 'media', prodotto_attivo: 'SI',
    stock_status: 'esaurito', stock_quantity: 0,
    data_ultimo_controllo_stock: '2026-05-22', note: 'Restock previsto giugno',
    created_at: '2026-05-01T00:00:00Z', updated_at: '2026-05-22T00:00:00Z',
  },
]

export const demoSettings: Setting[] = [
  { id: 's1', cliente_id: 'demo-silkincom',  chiave: 'automation_enabled',        valore: 'TRUE',           descrizione: 'Se FALSE nessun contenuto viene pubblicato',     updated_at: '2026-05-01T00:00:00Z' },
  { id: 's2', cliente_id: 'demo-silkincom',  chiave: 'dry_run',                   valore: 'TRUE',           descrizione: 'Se TRUE simula senza pubblicare',                updated_at: '2026-05-01T00:00:00Z' },
  { id: 's3', cliente_id: 'demo-silkincom',  chiave: 'timezone',                  valore: 'Europe/Rome',    descrizione: 'Timezone ufficiale del workflow',                updated_at: '2026-05-01T00:00:00Z' },
  { id: 's4', cliente_id: 'demo-silkincom',  chiave: 'max_retry',                 valore: '2',              descrizione: 'Numero massimo di retry automatici',             updated_at: '2026-05-01T00:00:00Z' },
  { id: 's5', cliente_id: 'demo-silkincom',  chiave: 'default_utm_campaign',      valore: 'social_default', descrizione: 'Campagna UTM di default',                        updated_at: '2026-05-01T00:00:00Z' },
  { id: 's6', cliente_id: 'demo-silkincom',  chiave: 'telegram_notifications',    valore: 'TRUE',           descrizione: 'Abilita notifiche Telegram',                     updated_at: '2026-05-01T00:00:00Z' },
  { id: 's7', cliente_id: 'demo-silkincom',  chiave: 'backup_enabled',            valore: 'TRUE',           descrizione: 'Abilita backup giornaliero',                     updated_at: '2026-05-01T00:00:00Z' },
  { id: 's8', cliente_id: 'demo-silkincom',  chiave: 'approval_required',         valore: 'TRUE',           descrizione: 'Pubblica solo contenuti approvati',              updated_at: '2026-05-01T00:00:00Z' },
  { id: 's9', cliente_id: 'demo-silkincom',  chiave: 'media_validation_required', valore: 'TRUE',           descrizione: 'Blocca contenuti con media non validi',          updated_at: '2026-05-01T00:00:00Z' },
  { id: 's10', cliente_id: 'demo-silkincom', chiave: 'stock_check_required',      valore: 'TRUE',           descrizione: 'Blocca prodotti non attivi o esauriti',          updated_at: '2026-05-01T00:00:00Z' },
]

export const demoLogs: LogPubblicazione[] = [
  { id: 'l1', cliente_id: 'demo-silkincom', timestamp: '2026-05-23T10:00:15Z', id_contenuto: 'C003', canale: 'tiktok',    formato: 'reel', status_precedente: 'IN_PUBBLICAZIONE', status_finale: 'PUBBLICATO',      blotato_post_id: 'blt_xyz_123', messaggio: 'ok', errore: null },
  { id: 'l2', cliente_id: 'demo-silkincom', timestamp: '2026-05-23T14:15:32Z', id_contenuto: 'C004', canale: 'facebook',  formato: 'post', status_precedente: 'IN_PUBBLICAZIONE', status_finale: 'ERRORE',          blotato_post_id: null,          messaggio: null, errore: 'media KO code=404' },
  { id: 'l3', cliente_id: 'demo-silkincom', timestamp: '2026-05-22T18:30:00Z', id_contenuto: 'C002', canale: 'instagram', formato: 'carousel', status_precedente: 'APPROVATO',     status_finale: 'DRY_RUN_OK',      blotato_post_id: null,          messaggio: 'Dry run simulato',         errore: null },
  { id: 'l4', cliente_id: 'demo-silkincom', timestamp: '2026-05-22T12:30:45Z', id_contenuto: 'C001', canale: 'instagram', formato: 'post', status_precedente: 'APPROVATO',     status_finale: 'DRY_RUN_OK',      blotato_post_id: null,          messaggio: 'Dry run simulato',         errore: null },
  { id: 'l5', cliente_id: 'demo-silkincom', timestamp: '2026-05-21T20:00:00Z', id_contenuto: 'C000', canale: 'instagram', formato: 'post', status_precedente: 'IN_PUBBLICAZIONE', status_finale: 'PUBBLICATO',      blotato_post_id: 'blt_aaa_001', messaggio: 'ok', errore: null },
]

export const demoClienti: Cliente[] = [
  {
    id: 'demo-silkincom',
    nome: 'SILKinCOM',
    slug: 'silkincom',
    settore: 'Fashion e-commerce',
    email: 'info@silkincom.com',
    telefono: null,
    piano: 'pro',
    contenuti_mese: 30,
    attivo: true,
    blog_domain: null,
    note: null,
    created_at: '2026-05-23T00:00:00Z',
    updated_at: '2026-05-23T00:00:00Z',
  },
]

export const demoBlogArticoli: BlogArticolo[] = [
  {
    id: 'b1', cliente_id: 'demo-silkincom', slug: 'come-abbinare-blazer-lino-estate',
    meta_title: 'Come abbinare il blazer in lino: guida pratica estate 2026',
    meta_description: 'Scopri 5 abbinamenti perfetti per il blazer in lino. Outfit casual, eleganti e da ufficio. Guida completa con foto e idee styling.',
    h1: 'Come abbinare il blazer in lino: 5 outfit pratici per l\'estate',
    intro: 'Il blazer in lino è il capo passe-partout dell\'estate: leggero, elegante, versatile. In questa guida scoprirai 5 modi per indossarlo, dal look ufficio al weekend.',
    sezioni: [
      { h2: 'Perché scegliere il blazer in lino', paragrafi: ['Il lino è un tessuto naturale traspirante, ideale per le alte temperature.', 'Resistente, durevole e con un look raffinato anche quando stropicciato.'], lista_punti: ['Traspirante', 'Naturale', 'Stiramento elegante'] },
      { h2: 'Outfit casual per il weekend', paragrafi: ['Abbina il blazer in lino beige a una t-shirt bianca e jeans dritti vita alta. Sneakers bianche per chiudere il look.'] },
      { h2: 'Look ufficio in estate', paragrafi: ['Pantalone palazzo color panna + camicia in seta + blazer in lino beige. Sandalo flat o mocassino.'] },
    ],
    faq: [
      { domanda: 'Si può lavare in lavatrice?', risposta: 'Sì, con programma delicato a 30°C. Stirare a vapore quando ancora leggermente umido.' },
      { domanda: 'Il lino si stropiccia molto?', risposta: 'È naturale che il lino abbia delle pieghe — fa parte del suo charme casual-elegante.' },
    ],
    cta_finale: 'Scopri il nostro blazer in lino sul sito',
    keywords_target: ['blazer lino', 'outfit estate', 'come abbinare blazer'],
    prodotti_linkati: ['P001'],
    tempo_lettura_min: 4,
    immagine_cover: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800',
    autore: 'Brand Editorial',
    status: 'DA_APPROVARE',
    data_pubblicazione: null, url_pubblicato: null,
    checked_seo: null, checked_copy: null,
    errore_tecnico: null,
    created_at: '2026-05-23T08:00:00Z', updated_at: '2026-05-23T08:00:00Z',
  },
]

export const demoSeoAudit: SeoAudit[] = [
  {
    id: 'a1', cliente_id: 'demo-silkincom', data_audit: '2026-05-19', periodo: 'settimanale',
    score_globale: 72,
    score_seo_tecnico: 85, score_seo_contenuti: 70, score_geo_ai_search: 58,
    score_social_coerenza: 80, score_eeat: 65, score_performance_social: 75,
    riepilogo: 'Brand solido su SEO tecnico e social. Da migliorare presenza GEO (citabilità AI) e segnali E-E-A-T (autorialità, recensioni).',
    punti_forti: ['Velocità sito eccellente (LCP 1.8s)', 'Schema Product completo', 'Tono brand coerente cross-canale', 'Engagement IG sopra media settore'],
    punti_critici: ['Manca llms.txt', 'Nessuna FAQ schema sulle PDP', 'Zero brand mentions su forum/Reddit', 'Bio TikTok senza link sito'],
    miglioramenti: [
      { area: 'geo_ai_search',   azione: 'Crea /llms.txt nella root del sito',                                 impatto: 'alto',  effort: 'basso', deadline_suggerita: '2026-05-26' },
      { area: 'geo_ai_search',   azione: 'Aggiungi FAQPage schema su 10 PDP top',                              impatto: 'alto',  effort: 'medio', deadline_suggerita: '2026-06-02' },
      { area: 'eeat',            azione: 'Pagina "Chi siamo" con foto + bio fondatori + certificazioni',      impatto: 'medio', effort: 'medio', deadline_suggerita: '2026-06-09' },
      { area: 'seo_contenuti',   azione: 'Pubblica 4 blog post pillar su "guide outfit"',                     impatto: 'alto',  effort: 'alto',  deadline_suggerita: '2026-06-15' },
      { area: 'social_coerenza', azione: 'Aggiungi link sito a bio TikTok',                                   impatto: 'basso', effort: 'basso', deadline_suggerita: '2026-05-24' },
    ],
    kpi_da_monitorare: [
      { metrica: 'Brand mentions AI (ChatGPT/Perplexity)', valore_attuale: '0', target: '5+ al mese' },
      { metrica: 'Backlink referring domains',             valore_attuale: '12', target: '25' },
      { metrica: 'Posizione media Google "blazer lino"',   valore_attuale: '#34', target: 'top 10' },
    ],
    contenuti_suggeriti: [
      { tema: 'Come abbinare blazer lino estate', formato: 'blog',     canale: 'blog',      priorita: 'alta' },
      { tema: 'Tutorial styling jeans vita alta', formato: 'reel',     canale: 'tiktok',    priorita: 'alta' },
      { tema: 'Outfit ufficio estate 5 idee',     formato: 'carousel', canale: 'instagram', priorita: 'media' },
    ],
    generato_da: 'claude-sonnet-4-6',
    created_at: '2026-05-19T21:00:00Z',
  },
]
